(package "repos-window"
         "0.1.0"
         "Reposition window if when needed")

(website-url "https://github.com/jcs-elpa/repos-window")
(keywords "convenience")

(package-file "repos-window.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "jcs-elpa")
(source "melpa")

(depends-on "emacs" "26.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
